import Link from 'next/link';
import { Check, FileText, Play, ShieldCheck, ArrowUpRight } from 'lucide-react';
import { BackLink, Footer, PlaceholderVisual, SiteHeader } from '../../components';
import { fypSections, gdpSections, projects } from '../../portfolio-data';

export function generateStaticParams() { return projects.slice(0, 2).map(project => ({ slug: project.slug })); }

export default async function ProjectDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const project = projects.find(item => item.slug === slug) ?? projects[0];
  const sections = project.slug === 'gdp' ? gdpSections : fypSections;
  const isGdp = project.slug === 'gdp';
  return <main><SiteHeader /><article className="case-study"><div className="case-top"><BackLink /><span className="eyebrow">{project.code} / CASE STUDY TEMPLATE</span></div><div className="case-hero"><div><span className="eyebrow">{project.label}</span><h1>{project.title}<br /><em>case study.</em></h1><p>{project.description}</p><div className="case-meta"><span><strong>STATUS</strong>{project.status}</span><span><strong>YEAR</strong>{project.year}</span><span><strong>TYPE</strong>{isGdp ? 'Collaborative' : 'Individual'}</span></div></div><PlaceholderVisual project={project} large /></div><div className="case-layout"><aside className="case-index"><span className="eyebrow">ON THIS RECORD</span>{sections.slice(0, 8).map(([title]) => <a key={title} href={`#${slugify(title)}`}>{title}</a>)}</aside><div className="case-body"><CaseSection id="project-overview" title="Project overview"><p>{project.description}</p><div className="callout"><ShieldCheck size={18} /><span>This page is an editable case-study scaffold. Replace marked copy, visuals, and metadata with verified project material.</span></div></CaseSection>{sections.slice(1).map(([title, copy]) => <CaseSection id={slugify(title)} title={title} key={title}><p>{copy}</p>{['System design', 'System architecture', 'Images and diagrams', 'Project gallery', 'Testing and results'].includes(title) && <div className="case-visual-slot"><PlaceholderVisual project={project} /><span>VISUAL SLOT / ADD DIAGRAM, PHOTO, OR RESULT</span></div>}{title === 'Objectives' && <ul className="check-list"><li><Check size={15} /> Define a measurable engineering objective.</li><li><Check size={15} /> Record the constraint or requirement it responds to.</li><li><Check size={15} /> Link the objective to evidence when content is added.</li></ul>}</CaseSection>)}<div className="case-next"><Link href={isGdp ? '/projects/fyp' : '/projects/gdp'}><span>Next record</span><strong>{isGdp ? 'Final Year Project' : 'Group Design Project'} <ArrowUpRight size={16} /></strong></Link></div></div></div></article><section className="case-cta"><div><span className="eyebrow">SUPPORTING MATERIALS</span><h2>Have a drawing, video, or report?</h2><p>Drop the final assets into the marked slots as the project documentation becomes available.</p></div><div className="case-cta-actions"><a className="button button-secondary" href="#"><FileText size={16} /> Add document</a><a className="button button-secondary" href="#"><Play size={16} /> Add video</a></div></section><Footer /></main>;
}

function CaseSection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section className="case-section" id={id}><span className="section-marker">/</span><h2>{title}</h2>{children}</section>; }
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }
