'use client';

import { ArrowLeft, ArrowUpRight, ExternalLink, Menu, X } from 'lucide-react';
import { useState, type AnchorHTMLAttributes, type ReactNode } from 'react';
import { education, experience, profile, projects, type Project } from './portfolio-data';

type InternalLinkProps = AnchorHTMLAttributes<HTMLAnchorElement> & { href: string; children?: ReactNode };
function Link({ children, ...props }: InternalLinkProps) { return <a {...props}>{children}</a>; }

export function Mark({ small = false }: { small?: boolean }) { return <span className={small ? 'mark mark-small' : 'mark'} aria-hidden="true"><span /><span /><span /></span>; }

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  const links = [['Projects', '/projects'], ['Experience', '/experience'], ['Education', '/education']];
  return <header className="site-header"><div className="site-header-inner"><Link href="/" className="wordmark" onClick={() => setOpen(false)}><Mark small /><span>Isameldin Ahmed</span></Link><nav className="desktop-nav" aria-label="Primary navigation">{links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}<a className="nav-project-link" href={`mailto:${profile.email}`}>Contact <ArrowUpRight size={14} /></a></nav><button className="menu-button" type="button" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(value => !value)}>{open ? <X size={21} /> : <Menu size={21} />}</button></div><div className={`mobile-nav ${open ? 'is-open' : ''}`}>{links.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}<ArrowUpRight size={16} /></Link>)}<a href={`mailto:${profile.email}`} onClick={() => setOpen(false)}>Contact <ArrowUpRight size={16} /></a></div></header>;
}

export function SectionIntro({ code, title, copy, action }: { code: string; title: string; copy?: string; action?: { label: string; href: string } }) { return <div className="section-intro"><div><span className="eyebrow">{code}</span><h2>{title}</h2></div>{copy && <p>{copy}</p>}{action && <Link className="text-link" href={action.href}>{action.label}<ArrowUpRight size={15} /></Link>}</div>; }

export function PhotoSlot({ code, title, label, large = false, accent = 'olive', image, fit = 'cover' }: { code: string; title: string; label: string; large?: boolean; accent?: string; image?: string; fit?: 'cover' | 'contain' }) { return <div className={`placeholder-visual accent-${accent} ${large ? 'placeholder-large' : ''} ${image ? 'has-image' : ''} ${image && fit === 'contain' ? 'image-fit-contain' : ''}`} aria-label={`${title}${image ? ' image' : ' image placeholder'}`} role="img">{image && <img src={image} alt={title} />}{!image && <><div className="visual-grid" /><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="visual-crosshair"><span /></div></>}<div className="visual-readout"><span>{code}</span><span>{image ? 'REPORT PHOTO' : 'PHOTO PLACEHOLDER'}</span></div><div className="visual-caption">{label}<br /><strong>{title}</strong></div></div>; }
export function PlaceholderVisual({ project, large = false, image, fit = 'cover' }: { project?: Project; large?: boolean; image?: string; fit?: 'cover' | 'contain' }) { return <PhotoSlot code={project?.code ?? 'IMG / 000'} title={project?.title ?? profile.name} label={project?.label ?? 'PORTRAIT / PLACEHOLDER'} large={large} accent={project?.accent ?? 'olive'} image={image ?? project?.image} fit={fit} />; }
export function Headshot() { return <div className="headshot-frame"><img src="/images/isameldin-headshot.jpg" alt="Professional headshot of Isameldin Ahmed" /><div className="headshot-corner" /><div className="headshot-label"><span>PORTRAIT / 001</span><strong>Isameldin Ahmed</strong></div></div>; }

export function ProjectCard({ project, compact = false }: { project: Project; compact?: boolean }) { return <article className={`project-card ${compact ? 'project-card-compact' : ''}`}><Link href={`/projects/${project.slug}`} className="project-image-link"><PlaceholderVisual project={project} /></Link><div className="project-card-top"><span>{project.code}</span><span>{project.year}</span></div><h3><Link href={`/projects/${project.slug}`}>{project.title}</Link></h3><p>{project.summary}</p><div className="tag-row">{project.tags.slice(0, 3).map(tag => <span key={tag}>{tag}</span>)}</div><Link className="card-link" href={`/projects/${project.slug}`}>View project <ArrowUpRight size={16} /></Link></article>; }

export function PageHeader({ code, title, emphasis, copy }: { code: string; title: string; emphasis: string; copy: string }) { return <section className="page-hero"><div><span className="eyebrow">{code}</span><h1>{title}<br /><em>{emphasis}</em></h1></div><p>{copy}</p></section>; }

export function FeaturedProjects() { return <section className="home-featured section"><SectionIntro code="Selected projects" title="Selected work." copy="The two projects that best represent your current engineering practice." action={{ label: 'Open project archive', href: '/projects' }} /><div className="featured-grid">{projects.slice(0, 2).map(project => <ProjectCard key={project.slug} project={project} />)}</div></section>; }

export function ExperiencePreview() { return <section className="home-experience section"><SectionIntro code="Work experience" title="Experience in practice." copy="Internship and APU engineering-lab work, with the full field log on its own page." action={{ label: 'Open experience page', href: '/experience' }} /><div className="home-experience-list">{experience.slice(0, 2).map((item, index) => <article className="home-experience-card" key={item.role}><span className="timeline-index">0{index + 1}</span><div><div className="timeline-heading"><h3>{item.role}</h3><span>{item.period}</span></div><p className="timeline-org">{item.organization}</p><p>{item.detail}</p><span className="mono-note">{item.tools}</span></div></article>)}</div></section>; }

export function EducationPreview() { return <section className="home-education section"><SectionIntro code="Education" title="Academic foundation." copy="A short view here, with the full academic record on its own page." action={{ label: 'Open education page', href: '/education' }} /><div className="education-preview-grid">{education.map((item, index) => <Link className="education-preview-card" href="/education" key={item.qualification}><PhotoSlot code={`EDU-0${index + 1}`} title={item.institution} label="EDUCATION / PHOTO SLOT" accent={index % 2 === 0 ? 'olive' : 'khaki'} /><div><span className="mono-note">{item.period}</span><h3>{item.qualification}</h3><p>{item.detail}</p></div></Link>)}</div></section>; }

export function ExperiencePageBody() { return <div className="page-body experience-page-body"><div className="experience-photo-band"><PhotoSlot code="EXP-00" title="Internship team" label="AMBANI CONSORTIUM GROUP" large accent="red" image={experience[1].image} /><div><span className="eyebrow muted">WORKING CONTEXT</span><h2>Labs, industry, and responsibility.</h2><p>From supporting engineering students at APU to working on generator monitoring and technical design during an industry internship, these roles show how I work with people, tools, and constraints.</p></div></div><div className="full-timeline">{experience.map((item, index) => <article className="experience-entry" key={item.role}><span className="timeline-index">0{index + 1}</span><div className="experience-entry-copy"><div className="timeline-heading"><h2>{item.role}</h2><span>{item.period}</span></div><p className="timeline-org">{item.organization}</p><p>{item.detail}</p><span className="mono-note">{item.tools}</span></div><PhotoSlot code={`EXP-0${index + 1}`} title={item.organization} label={item.image ? 'INTERNSHIP REPORT PHOTO' : 'EXPERIENCE / PHOTO SLOT'} accent={index % 2 === 0 ? 'olive' : 'khaki'} image={item.image} /></article>)}</div><div className="experience-note"><span className="eyebrow">SUPPORTING IMAGES</span><p>Add photos of your workplace, lab, field environment, tools, team, or completed work when you are ready. Do not include confidential material.</p></div></div>; }

export function EducationPageBody() { return <div className="page-body education-page-body"><div className="education-record"><div><span className="eyebrow muted">ACADEMIC RECORD</span><h2>A foundation in mechatronics.</h2><p>I completed a Bachelor of Mechatronic Engineering with Honours at Asia Pacific University through a dual DMU degree programme, graduating with Second Class Upper Division.</p></div><PhotoSlot code="EDU-00" title="Campus or education photo" label="EDUCATION / FEATURE IMAGE" large accent="olive" /></div><div className="education-detail-list">{education.map((item, index) => <article className="education-detail" key={item.qualification}><span className="mono-note">{item.period}</span><div><h2>{item.qualification}</h2><p className="timeline-org">{item.institution}</p><p>{item.detail}</p><div className="tag-row"><span>QUALIFICATION</span><span>ACADEMIC RECORD</span><span>PHOTO SLOT</span></div></div><PhotoSlot code={`EDU-0${index + 1}`} title={item.qualification} label="EDUCATION / SUPPORTING PHOTO" accent="khaki" /></article>)}</div></div>; }

export function HomeSections() { return <section id="contact" className="section section-contact"><div className="contact-panel"><div><span className="eyebrow">Contact</span><h2>Have a system to build?</h2><p>For engineering roles, collaborations, or a thoughtful technical conversation, send a message and I will get back to you.</p></div><a className="button button-primary" href={`mailto:${profile.email}?subject=Engineering opportunity`}>Start a conversation <ArrowUpRight size={17} /></a></div></section>; }

function TimelineItem({ index, title, organization, period, detail, meta }: { index: number; title: string; organization: string; period: string; detail: string; meta?: string }) { return <article className="timeline-item"><span className="timeline-index">0{index + 1}</span><div><div className="timeline-heading"><h3>{title}</h3><span>{period}</span></div><p className="timeline-org">{organization}</p><p>{detail}</p>{meta && <span className="mono-note">{meta}</span>}</div></article>; }

export function Footer() { return <footer className="site-footer"><div><Link href="/" className="wordmark"><Mark small /><span>Isameldin Ahmed</span></Link><p>Mechatronics engineering portfolio<br />Kuala Lumpur, Malaysia</p></div><div className="footer-links"><a href={`mailto:${profile.email}`}>{profile.email}</a><a href={`tel:${profile.phone.replace(/\s/g, '')}`}>{profile.phone}</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ExternalLink size={13} /></a><a href={profile.website} target="_blank" rel="noreferrer">Website <ExternalLink size={13} /></a></div><span className="mono-note">OPEN TO ENGINEERING WORK</span></footer>; }
export function BackLink() { return <Link className="back-link" href="/"><ArrowLeft size={16} /> Back to home</Link>; }
