export type Project = {
  slug: string;
  code: string;
  title: string;
  label: string;
  summary: string;
  description: string;
  year: string;
  status: string;
  category: string;
  tags: string[];
  accent: string;
  image?: string;
  gallery?: string[];
  galleryItems?: GalleryItem[];
  designItems?: GalleryItem[];
  external?: string;
  report?: string;
};

export type GalleryItem = {
  image: string;
  code: string;
  title: string;
  label: string;
  description: string;
};

export const profile = {
  name: 'Isameldin Ahmed',
  fullName: 'Isameldin Ahmed Hussein Ahmed',
  title: 'Mechatronics Engineering Graduate',
  location: 'Kuala Lumpur, Malaysia',
  email: 'eldeenisam@gmail.com',
  phone: '+60 11-3900 9572',
  linkedin: 'https://linkedin.com/in/isameldin',
  github: 'https://github.com/',
  website: 'https://isameldin.netlify.app',
  tagline: 'I build, automate, and improve the things around me.',
  intro: 'I am a passionate mechatronics engineering graduate with experience in mechanical design and IoT systems development, plus hands-on academic work in robotics, automation, embedded systems, and control. I enjoy turning a practical problem into a system that I can test, understand, and improve.',
};

export const projects: Project[] = [
  { slug: 'fyp', code: 'FYP-01', title: 'EMG-Controlled Prosthetic Arm', label: 'FINAL YEAR PROJECT', summary: 'I developed a 3D-printed HACKberry prosthetic arm with EMG control, sensory feedback, safety responses, and an ESP32-based control system.', description: 'I developed a modified HACKberry prosthetic arm controlled by surface EMG signals. My Phase 2 system combines an ESP32, servo-driven movement, thermistor and piezoelectric sensing, vibration feedback, safety responses, and a web-based calibration dashboard.', year: '2026', status: 'Final year project', category: 'Embedded Systems', tags: ['ESP32', 'EMG', 'Sensors', 'Dashboard'], accent: 'red', image: '/images/projects/fyp/hackberry-platform.jpg', report: '/documents/isameldin-ahmed-fyp-phase-2-report.pdf', gallery: ['/images/projects/fyp-prosthetic-arm.jpg', '/images/projects/fyp-assembly.jpg', '/images/projects/fyp-testing.jpg'], galleryItems: [
    { image: '/images/projects/fyp/hackberry-platform.jpg', code: 'FYP-02', title: 'HACKberry arm platform', label: 'REFERENCE PLATFORM', description: 'I used the open-source HACKberry arm as the mechanical starting point, then adapted its platform with added wrist and elbow movement, EMG control, and sensory feedback.' },
    { image: '/images/projects/fyp/cad-side-view.png', code: 'FYP-03', title: 'Modified prosthetic arm CAD', label: 'MECHANICAL DESIGN', description: 'I arranged the adapted hand, wrist interface, and forearm casing around the servo-driven mechanism, wiring, and embedded electronics in this side-view CAD model.' },
    { image: '/images/projects/fyp/system-architecture.png', code: 'FYP-04', title: 'Updated system architecture', label: 'SYSTEM ARCHITECTURE', description: 'I mapped the signal path from muscle input and single-channel EMG acquisition through ESP32 sampling, signal processing, classification, control, sensing, calibration, actuation, and vibration feedback.' },
    { image: '/images/projects/fyp/emg-dashboard.png', code: 'FYP-05', title: 'EMGARM calibration dashboard', label: 'SOFTWARE INTERFACE', description: 'I brought the live EMG envelope, pulse features, curve shape, calibration values, and training states into one workspace for configuring prosthetic gestures.' },
    { image: '/images/projects/fyp/emg-test.png', code: 'FYP-06', title: 'Live EMG signal test', label: 'EXPERIMENTAL TESTING', description: 'I connected surface EMG electrodes during a live test and streamed muscle activation data to the dashboard for signal inspection and gesture classification.' },
    { image: '/images/projects/fyp/prototype.jpg', code: 'FYP-07', title: 'Integrated physical prototype', label: 'SYSTEM INTEGRATION', description: 'I assembled the 3D-printed hand, forearm casing, wrist module, and embedded hardware into a working physical prototype.' },
    { image: '/images/projects/fyp/distance-response.png', code: 'FYP-08', title: 'Distance response results', label: 'RESULTS / VALIDATION', description: 'I recorded the measured thumb-index distance across 30 trials to evaluate the prosthetic movement response during testing.' },
  ] },
  { slug: 'gdp', code: 'GDP-02', title: 'Automated Guided Vehicle for Hospitals', label: 'GROUP DESIGN PROJECT', summary: 'I designed a hospital logistics AGV to transport medical supplies and biohazard waste using ROS2 navigation, LiDAR, camera sensing, and a modular aluminium chassis.', description: 'I designed the AGV chassis and navigation hardware for a hospital logistics vehicle intended to carry medical supplies and biohazard waste. The report documents my SolidWorks chassis, suspension and sensor brackets, ROS2 navigation approach, LiDAR and camera integration, and Jetson and ESP32 control hardware.', year: '2026', status: 'Group design project', category: 'Robotics', tags: ['ROS2', 'LiDAR', 'SolidWorks', 'Jetson'], accent: 'olive', image: '/images/projects/gdp/agv-cover-platform.jpg', report: '/documents/gdp-report-agv-group.pdf', galleryItems: [
    { image: '/images/projects/gdp/chassis-frame.jpg', code: 'GDP-03', title: 'Fabricated AGV chassis frame', label: 'MECHANICAL STRUCTURE', description: 'I used aluminium extrusion to create a stable 120 cm by 100 cm chassis platform for the drive system, payload area, batteries, and navigation hardware.' },
    { image: '/images/projects/gdp/initial-frame-build.jpg', code: 'GDP-04', title: 'Initial frame build', label: 'PROTOTYPE ASSEMBLY', description: 'I translated the SolidWorks concept into a physical platform and established the mounting points used during later integration.' },
    { image: '/images/projects/gdp/lighting-assembly.jpg', code: 'GDP-05', title: 'Front lighting and sensor hardware', label: 'HARDWARE INTEGRATION', description: 'I mounted the lighting module and sensor support hardware to the aluminium frame for operation in indoor hospital environments.' },
    { image: '/images/projects/gdp/suspension-bracket.jpg', code: 'GDP-06', title: 'Suspension bracket implementation', label: 'FABRICATION DETAIL', description: 'I used a custom PLA+ bracket, M6 fasteners, and deliberate alignment to secure the suspension strut to the 45 by 45 mm extrusion and transfer loads during motion.' },
    { image: '/images/projects/gdp/lidar-bracket.jpg', code: 'GDP-07', title: 'LiDAR mounting solution', label: 'NAVIGATION HARDWARE', description: 'I positioned the Unitree 4D LiDAR above the chassis for a clear scanning view while preserving space for the camera and other front-mounted hardware.' },
    { image: '/images/projects/gdp/gazebo-simulation.jpg', code: 'GDP-08', title: 'Gazebo navigation simulation', label: 'ROS2 VALIDATION', description: 'I used Gazebo to test the navigation stack around static warehouse-style obstacles, using sensor data with global and local path planning before real-world deployment.' },
    { image: '/images/projects/gdp/electronics-layout.jpg', code: 'GDP-09', title: 'Integrated electronics layout', label: 'SYSTEM INTEGRATION', description: 'I recorded the placement of the battery, motor hubs, emergency stop, wiring, and LiDAR on the completed platform to support balanced integration and cable management.' },
  ], designItems: [
    { image: '/images/projects/gdp/payload-enclosure-cad.jpg', code: 'GDP-CAD-01', title: 'Payload enclosure concept', label: 'SOLIDWORKS / 3D DESIGN', description: 'I modelled the enclosure concept around the AGV frame to create a dedicated structure for carrying hospital supplies and biohazard waste.' },
    { image: '/images/projects/gdp/suspension-attachment-cad.jpg', code: 'GDP-CAD-02', title: 'Suspension frame attachment', label: 'SOLIDWORKS / 3D DESIGN', description: 'I designed the suspension attachment around the 45 by 45 mm aluminium profile so the strut could be aligned with the chassis and secured with fasteners.' },
    { image: '/images/projects/gdp/suspension-hole-cad.png', code: 'GDP-CAD-03', title: 'Suspension bracket detail', label: 'SOLIDWORKS / DETAIL VIEW', description: 'I used this CAD detail to position the suspension strut and transfer loads into the frame through the machined opening and mounting geometry.' },
    { image: '/images/projects/gdp/lidar-mount-cad.jpg', code: 'GDP-CAD-04', title: 'Unitree 4D LiDAR mount', label: 'SOLIDWORKS / NAVIGATION', description: 'I designed the LiDAR plate with the required mounting pattern and dimensions so the sensor could sit at a clear scanning height above the vehicle.' },
  ] },
  { slug: 'suspension-fea', code: 'FEA-03', title: 'Crankshaft FEA and Optimization', label: 'FINITE ELEMENT ANALYSIS', summary: 'I evaluated a crankshaft with modal, torsional, and model-reduction analysis, then compared material and geometry improvements for AMR use.', description: 'I used Altair analysis to study the vibration and torsional behaviour of a crankshaft intended for heavy-duty autonomous mobile robots. I examined natural frequencies, mode shapes, torsion rigidity, model reduction, and a possible 4340 steel optimization.', year: '2025', status: 'Completed academic project', category: 'Mechanical Design', tags: ['Altair', 'FEA', 'Modal Analysis', 'Optimization'], accent: 'olive', image: '/images/projects/fea/crankshaft-cover.jpg', galleryItems: [
    { image: '/images/projects/fea/crankshaft-mesh.jpg', code: 'FEA-04', title: 'Crankshaft analysis model', label: 'FEA / MESH', description: 'I prepared the crankshaft model for finite element analysis and used the mesh as the basis for evaluating its dynamic response.' },
    { image: '/images/projects/fea/mode-1-response.jpg', code: 'FEA-05', title: 'Mode 1 response', label: 'MODAL ANALYSIS', description: 'I identified the first natural frequency at 27.14 Hz, representing the most critical global bending mode for resonance consideration.' },
    { image: '/images/projects/fea/mode-2-response.jpg', code: 'FEA-06', title: 'Mode 2 response', label: 'MODAL ANALYSIS', description: 'I compared the higher-order bending behaviour at 175 Hz and reviewed how the deformation was distributed across the crankshaft.' },
    { image: '/images/projects/fea/torsion-rigidity.jpg', code: 'FEA-07', title: 'Torsion rigidity analysis', label: 'TORSIONAL RESPONSE', description: 'I evaluated the crankshaft under a 200 Nm torque and reviewed the stress concentration near the pulley end.' },
    { image: '/images/projects/fea/model-reduction.png', code: 'FEA-08', title: 'Model reduction analysis', label: 'MODEL REDUCTION', description: 'I used model reduction to study the low-frequency global motion and separate rigid-body movement from internal deformation.' },
  ] },
  { slug: 'cam-lidar-mount', code: 'CAM-04', title: 'LiDAR Mount CAM and Toolpaths', label: 'SOLIDWORKS CAM / CNC', summary: 'I designed and prepared an aluminium LiDAR mounting plate for 3-axis CNC machining, then used topology results to reduce unnecessary mass.', description: 'I designed a LiDAR mounting plate for an autonomous mobile robot and simulated its manufacture using SolidWorks CAM. I defined the machine setup, coordinate system, stock, machining features, toolpaths, and a redesigned plate after topology optimization.', year: '2025', status: 'Completed academic project', category: 'Mechanical Design', tags: ['SolidWorks CAM', 'CNC', 'Toolpaths', 'Topology'], accent: 'khaki', image: '/images/projects/cam/lidar-mount-cover.jpg', galleryItems: [
    { image: '/images/projects/cam/lidar-mount-drawing.png', code: 'CAM-05', title: 'LiDAR mount design', label: 'CAD / COMPONENT DESIGN', description: 'I defined the plate geometry, mounting holes, central features, and slots around the functional requirements of the LiDAR assembly.' },
    { image: '/images/projects/cam/topology-study.png', code: 'CAM-06', title: 'Topology study', label: 'DESIGN OPTIMIZATION', description: 'I used the topology study to identify areas where material could be removed while maintaining the critical load paths and stiffness of the plate.' },
    { image: '/images/projects/cam/redesigned-lidar-plate.jpg', code: 'CAM-07', title: 'Redesigned LiDAR plate', label: 'WEIGHT REDUCTION', description: 'I redesigned the plate around the topology results to improve its weight-to-strength balance before regenerating the machining process.' },
    { image: '/images/projects/cam/machined-lidar-plate.png', code: 'CAM-08', title: 'Machining simulation', label: 'SOLIDWORKS CAM / TOOLPATH', description: 'I verified the revised toolpath sequence for facing, drilling, pocketing, and contour operations on a 3-axis CNC setup.' },
  ] },
  { slug: 'machine-vision-mushroom-inspection', code: 'MVI-05', title: 'Mushroom Disease Inspection', label: 'MACHINE VISION / AI', summary: 'I built a mushroom inspection system that combines OpenCV disease detection, Roboflow and YOLOv8 inference, and a GUI for multiple inspection tasks.', description: 'I worked on a group machine-vision assignment focused on White Enoki mushroom inspection. My individual tasks covered traditional OpenCV classification of bacterial, fungal, and physiological disease, plus a Roboflow and YOLOv8 model for disease detection. I also helped integrate the inspection tools into a Tkinter GUI.', year: '2025', status: 'Completed academic project', category: 'Electronics', tags: ['OpenCV', 'YOLOv8', 'Roboflow', 'Python'], accent: 'red', image: '/images/projects/mvi/enoki-mushrooms-cover.jpg', galleryItems: [
    { image: '/images/projects/mvi/disease-classification.jpg', code: 'MVI-06', title: 'OpenCV disease classification', label: 'TRADITIONAL COMPUTER VISION', description: 'I classified bacterial, fungal, and physiological disease using contour area, circularity, aspect ratio, thresholding, and bounding boxes.' },
    { image: '/images/projects/mvi/roboflow-disease-results.png', code: 'MVI-07', title: 'Roboflow disease results', label: 'YOLOV8 / AI INFERENCE', description: 'I trained and deployed a Roboflow and YOLOv8 model to identify disease regions and return class labels with confidence values.' },
    { image: '/images/projects/mvi/inspection-gui.png', code: 'MVI-08', title: 'Inspection GUI', label: 'PYTHON / TKINTER', description: 'I integrated the inspection options into a Tkinter interface so a user can choose a model, camera or video input, and the required analysis task.' },
    { image: '/images/projects/mvi/inspection-flowchart.png', code: 'MVI-09', title: 'Integrated inspection flow', label: 'SYSTEM INTEGRATION', description: 'I mapped the flow from model selection and input choice through OpenCV or Roboflow processing and the final inspection result.' },
    { image: '/images/projects/mvi/gui-disease-results.jpg', code: 'MVI-10', title: 'GUI disease inspection result', label: 'RESULTS', description: 'I tested the integrated interface with disease inspection output and bounding-box labels over the mushroom images.' },
    { image: '/images/projects/mvi/image-segmentation.jpg', code: 'MVI-11', title: 'Image segmentation', label: 'ADDITIONAL INSPECTION TASK', description: 'I added image segmentation as one of the supporting inspection modes available through the integrated interface.' },
    { image: '/images/projects/mvi/distance-detection.jpg', code: 'MVI-12', title: 'Distance detection', label: 'ADDITIONAL INSPECTION TASK', description: 'I added distance measurement as another inspection mode, showing the measured object span on the processed frame.' },
  ] },
  { slug: 'industrial-automation', code: 'PLC-06', title: 'Industrial Automation Systems', label: 'PLC / CONTROL LOGIC', summary: 'I worked on two PLC-controlled systems covering conveyor movement, item sorting, sizing, and stamping sequences.', description: 'I contributed to two independent PLC-controlled systems using physical hardware and simulation. One moved objects between fixed conveyor positions. The other sorted items by size and stamped them using ladder logic.', year: 'Academic project', status: 'Completed academic work', category: 'Automation', tags: ['PLC', 'Ladder Logic', 'Conveyors', 'Simulation'], accent: 'khaki' },
  { slug: 'smart-city-health', code: 'IOT-07', title: 'Smart City Health Monitoring', label: 'IOT / MONITORING', summary: 'I developed an academic IoT system for sensor data acquisition, remote monitoring, and pollution control concepts.', description: 'I developed an IoT smart city health monitoring system focused on collecting sensor data, supporting remote monitoring, and exploring pollution control responses.', year: 'Academic project', status: 'Completed academic work', category: 'Electronics', tags: ['IoT', 'Sensors', 'Monitoring'], accent: 'red' },
  { slug: 'robot-mapping', code: 'ROS-08', title: 'Robot Mapping and Navigation', label: 'ROS2 / ROBOTICS', summary: 'I built my understanding of ROS2 through robot mapping and navigation exercises.', description: 'I worked with ROS2 concepts through robot mapping and navigation exercises. I can add the specific robot platform, maps, screenshots, and results when the supporting material is ready.', year: 'Academic experience', status: 'Documentation slot', category: 'Robotics', tags: ['ROS2', 'Mapping', 'Navigation'], accent: 'olive' },
  { slug: 'train-scheduling', code: 'PY-09', title: 'Train Scheduling System', label: 'PYTHON / PROGRAMMING', summary: 'I developed a Python scheduling system as part of my academic programming experience.', description: 'I programmed a train scheduling system using Python. I can add the scheduling logic, interface, and examples of the final system when the project files are available.', year: 'Academic experience', status: 'Documentation slot', category: 'Programming', tags: ['Python', 'Scheduling', 'Logic'], accent: 'khaki' },
  { slug: 'leave-management', code: 'C-10', title: 'Leave Management System', label: 'C / PROGRAMMING', summary: 'I developed a C-based leave management system as additional academic programming experience.', description: 'I programmed a leave management system using C. I can add the system flow, data model, and screenshots when the project files are available.', year: 'Academic experience', status: 'Documentation slot', category: 'Programming', tags: ['C', 'Data Structures', 'Systems'], accent: 'red' },
  { slug: 'solidworks-submarine', code: 'CAD-11', title: 'Submarine Design', label: 'SOLIDWORKS / CAD', summary: 'I completed a SolidWorks mechanical design study focused on a submarine concept.', description: 'I designed a submarine using SolidWorks. I can add the model views, design constraints, drawings, and rendering later.', year: 'Academic experience', status: 'Documentation slot', category: 'Mechanical Design', tags: ['SolidWorks', '3D CAD', 'Design'], accent: 'olive' },
  { slug: 'vacuum-pick-and-place', code: 'PLC-12', title: 'Electro-Pneumatic Pick and Place', label: 'OMRON PLC / AUTOMATION', summary: 'I worked on an electro-pneumatic vacuum pick-and-place device controlled with an Omron PLC.', description: 'I worked on an electro-pneumatic vacuum pick-and-place device using an Omron PLC. I can add the pneumatic schematic, sequence logic, and machine photos later.', year: 'Academic experience', status: 'Documentation slot', category: 'Automation', tags: ['Omron PLC', 'Pneumatics', 'Pick and Place'], accent: 'khaki' },
  { slug: 'digital-circuits', code: 'ELEC-13', title: 'Digital and Analogue Circuit Studies', label: 'CIRCUIT DESIGN', summary: 'I studied circuit design through an ALU controller and a BJT amplifier.', description: 'I constructed an ALU controller circuit for digital electronics and designed a BJT amplifier circuit for analogue electronics. I can add circuit diagrams and measured waveforms later.', year: 'Academic experience', status: 'Documentation slot', category: 'Electronics', tags: ['Digital Circuits', 'Analogue Circuits', 'LTspice'], accent: 'red' },
  { slug: 'soft-drink-production', code: 'LABVIEW-14', title: 'Soft Drink Production System', label: 'LABVIEW / PROCESS', summary: 'I studied an automated soft drink production process using LabVIEW.', description: 'I designed a soft drink production system using LabVIEW. I can add the process flow, HMI screenshots, and control logic later.', year: 'Academic experience', status: 'Documentation slot', category: 'Programming', tags: ['LabVIEW', 'Process Control', 'HMI'], accent: 'olive' },
];

export const experience = [
  { period: 'DEC 2022 - JUL 2026', role: 'Senior Engineering Technical Assistant', organization: 'Asia Pacific University', detail: 'I was promoted to lead a team of lab assistants while supporting 20 to 50 students per semester across engineering lab sessions. I guided students with 3D printers, oscilloscopes, robotic arms, PLC units, and digital and analogue signal training kits.', tools: '3D Printing / Oscilloscopes / Robotic Arms / PLCs / Sensor Calibration' },
  { period: 'MAR - SEP 2026', role: 'Mechatronics Engineering Intern', organization: 'Ambani Consortium Group (M) Sdn. Bhd.', detail: 'I designed brackets and technical drawings for generator housings, tested an LTE module for remote generator monitoring and control, applied DFM and Poka-Yoke principles, and supported technical coordination and client engagement for the 2025 Invest Zambia International Conference.', tools: 'SolidWorks / LTE / IoT Monitoring / DFM / Poka-Yoke / ISO 9001, 14001, 45001', image: '/images/experience/internship-team.jpg' },
  { period: 'DEC 2024', role: 'Engineering Technical Assistant', organization: 'Asia Pacific University', detail: 'I maintained and repaired lab equipment, including 3D printers, oscilloscopes, robotic arms, PLC units, and Arduino kits. I supported 30 to 40 students per semester with sensor calibration and analogue circuit design while following lab safety procedures.', tools: 'Arduino / PLCs / Oscilloscopes / Lab Safety / Circuit Design' },
];

export const volunteering = [
  { period: 'AUG 2024 - MAY 2026', role: 'Head of Public Relations', organization: 'Institution of Mechanical Engineers, APU Student Section', detail: 'I led communications, built industry partnerships, invited speakers, spoke at events, and helped organize more than 20 workshops, competitions, and events.' },
];

export const education = [
  { period: 'JUN 2022 - JUN 2026', qualification: 'Bachelor of Mechatronic Engineering with Honours', institution: 'Asia Pacific University', detail: 'I completed the dual DMU Degree Programme with Second Class Upper Division, including the De Montfort University award from Leicester.' },
  { period: 'JAN 2020 - NOV 2021', qualification: 'A Levels', institution: 'LICEF School, Lusaka, Zambia', detail: 'I achieved A in Physics, B in Chemistry, and B in Mathematics, and I graduated as high school valedictorian.' },
];

export const certificates = ['MATLAB Onramp', 'Simulink Onramp', 'Control Design Onramp with Simulink', 'Introduction to IoT', 'Python', 'C', 'Lean Six Sigma White Belt'];
export const skills = [
  { label: 'Programming and embedded systems', items: 'C, Python, MATLAB, Arduino, ESP32, machine vision, ROS2' },
  { label: 'Circuit design and CAD', items: 'Digital circuit design, SOLIDWORKS, Fusion 360, 2D engineering drawings, 3D printing' },
  { label: 'Automation and controls', items: 'PLC programming and control, stepper and servo motor control, sensor integration and calibration' },
  { label: 'Simulation and tools', items: 'Simulink, ABB RobotStudio, LabVIEW, Automation Studio, CX Programmer, LTspice, Multisim, Altair' },
];
export const awards = ['High School Valedictorian, LICEF Secondary School, Lusaka, Zambia', 'Al-Khayyam Mathematics Award, LICEF Secondary School, Lusaka, Zambia'];

export const fypSections = [
  ['Project overview', 'I adapted the open-source HACKberry prosthetic arm design and modified it to add EMG muscle-signal control for hand movement. My build combines an ESP32, sensor feedback, haptic vibration, safety responses, and an online dashboard.'],
  ['Problem statement', 'I identified that many prosthetic arms remain out of reach because of high purchase, maintenance, and rehabilitation costs. Lower-cost alternatives can provide limited movement and little or no sensory feedback, reducing their usefulness in daily activities.'],
  ['Aim', 'I aimed to develop a 3D-printed prosthetic arm controlled by electromyography signals that also provides environmental feedback through integrated sensors.'],
  ['Objectives', 'I set out to process EMG signals to control the five fingers, palm, and elbow with a target accuracy of at least 70%, develop feedback for surface roughness and temperature, adapt an existing arm into a low-cost 3D-printed system, and evaluate movement accuracy and task success.'],
  ['Research justification', 'I combined 3D printing, embedded control, and sensory feedback to explore a more affordable and adaptable assistive device. I used personalised EMG calibration to make the system more intuitive while reducing dependence on expensive proprietary hardware.'],
  ['My role and responsibilities', 'I adapted and 3D-printed the HACKberry design, modified the arm, integrated the ESP32 and sensors, developed the control and dashboard functions, and tested and improved the muscle-signal response.'],
  ['System design', 'I used the ESP32 as the central controller for single-channel EMG acquisition, signal conditioning, feature extraction, movement classification, actuator control, and sensor data. I connected a Wi-Fi dashboard for calibration, while piezoelectric sensing, a vibration motor, and a thermistor provided texture feedback and heat protection.'],
  ['Methodology', 'I followed a design, build, calibrate, test, and refine cycle. I filtered, rectified, smoothed, and mapped EMG signals to movement thresholds before integrating the mechanical system, actuator mounts, sensing hardware, and dashboard.'],
  ['Design changes', 'I used a single EMG channel to reduce setup complexity and processing load. I stored user-specific calibration values in ESP32 non-volatile memory and added an active wrist mechanism and integrated elbow structure to improve movement range and load distribution.'],
  ['Hardware and software', 'I used the HACKberry prosthetic-arm design, 3D-printed parts, an ESP32 microcontroller, EMG input, thermistors, pressure sensors, vibration feedback, analogue signal conditioning, digital signal processing, and a web-based dashboard.'],
  ['Technical specifications', 'I used seven servo motors for actuation, an ESP32 for embedded processing, surface EMG electrodes, PLA and PETG printed parts, a piezoelectric sensor, an NTC thermistor, and a vibration motor. My report estimates the component cost at RM546.'],
  ['Development process', 'I started from an open-source arm design, modified the mechanical structure, integrated control electronics and sensing, connected the dashboard, and refined the control response through testing.'],
  ['Testing and results', 'I tested EMG-to-distance mapping, servo response latency, power consumption, grip repeatability, and piezoelectric texture sensing. My report records control accuracy above 90% across the tested EMG states, internal response latency of 20 to 68 ms, and fingertip gaps from 1.5 to 2.4 mm across five repeated grips.'],
  ['Challenges and solutions', 'I reduced signal noise with high-pass, notch, and low-pass filtering, followed by user calibration. I addressed mechanical backlash and printed-part alignment through servo calibration, tendon adjustment, and reinforced components.'],
  ['Key achievements', 'I delivered a standalone ESP32-based prototype with seven controllable degrees of freedom across the fingers, wrist, and elbow. My system combines personalised EMG control, web calibration, texture feedback, heat protection, vibration feedback, and local storage of user parameters.'],
  ['Sustainability and accessibility', 'I used open-source foundations, additive manufacturing, modular parts, and commercially available electronics to support repair and adaptation. The low estimated component cost is intended to reduce barriers to assistive technology, while I also recognised the need to manage electronic waste and design for disassembly.'],
  ['Limitations', 'I found that the single-channel EMG system limits simultaneous movement commands and requires recalibration for different users. Texture sensing can be affected by mounting position and vibration, and my controlled validation setting requires wider clinical testing.'],
  ['Lessons learned', 'I learned that mechanical design, analogue signal conditioning, embedded programming, sensor integration, control logic, and user-facing software must work together. The project reinforced the importance of calibration, repeatable testing, safe limits, and designing around real user variability.'],
  ['Future improvements', 'I would investigate multi-channel EMG with richer classification, closed-loop grip-force sensing, lighter actuators, improved power management, and broader trials with clinical representatives and diverse users.'],
];

export const gdpSections = [
  ['Project overview', 'I worked on a smart automated guided vehicle for hospital logistics. The intended use is secure transport of medical supplies and biohazard waste while reducing manual handling and supporting safer movement through hospital environments.'],
  ['Problem statement', 'I identified that hospital staff spend significant time moving food, medicine, equipment, and waste. Manual transport creates physical strain, takes staff away from patient care, can introduce delivery errors, and becomes harder to scale across larger hospital buildings.'],
  ['Aim and objectives', 'I aimed to design and build a working prototype of a smart AGV for secure hospital transport. The objectives were to develop autonomous navigation, implement secure dual-payload compartments using RFID authentication, design an automatic obstacle-stop safety system, and test the AGV implementation.'],
  ['Team members', 'I worked with Ayser Amir Kamil Mohamed, Badr Bassam Hassan Albdulmajeed, and Rayan Khalid Mubarak Al Yaquobi under the supervision of Dr. Sathish Kumar Selvaperumal.'],
  ['My individual contribution', 'Isameldin Ahmed focused on the AGV design and navigation section. This included SolidWorks schematics for the chassis, suspension bracket, LiDAR mount, and camera mount, together with the ROS2-based navigation approach using LiDAR and camera inputs.'],
  ['System architecture', 'I used LiDAR and camera data as environmental input. Sensor fusion and SLAM estimate the AGV position and generate a map, A* selects a global route, and a local planner adjusts the trajectory for obstacle avoidance. I passed navigation commands to the ESP32 motor-control layer, with the Jetson Orin Nano supporting the higher-level computing environment.'],
  ['Design process', 'I began with a 120 cm by 100 cm chassis concept and aluminium extrusion members. I designed custom brackets for the suspension, Unitree 4D LiDAR, and ZED 2i camera, then carried those decisions into fabrication, assembly, and system integration.'],
  ['Hardware and software', 'I used ROS2, LiDAR, camera-based machine vision, an ESP32, an NVIDIA Jetson Orin Nano, SolidWorks, Gazebo, SLAM, A* global planning, local obstacle avoidance, and YOLOv8 models for vision tasks.'],
  ['Technical specifications', 'I documented a 120 cm by 100 cm chassis using 45 by 45 mm and 40 by 80 mm aluminium profiles. I designed a suspension attachment with a 29.5 mm strut opening and M6 fasteners, plus a 100 mm by 60 mm LiDAR mount with M3 sensor fasteners and M4 chassis mounting holes.'],
  ['Testing and results', 'I documented a Gazebo simulation with static obstacles, a LiDAR and camera configuration aligned with the physical platform, and an integrated chassis with motor hubs, battery, emergency stop, wiring, camera, and LiDAR placement. The broader integrated-system chapter also records vision, access-control, dashboard, and motor-control testing.'],
  ['Challenges and solutions', 'I addressed hospital navigation requirements through LiDAR and camera sensing, SLAM, global and local planning, deliberate sensor placement, and a modular chassis that supports adjustment and maintenance.'],
  ['Key achievements', 'I produced a documented AGV chassis and navigation platform with custom mechanical mounts, a ROS2 navigation strategy, LiDAR and camera integration, and an embedded control path linking navigation commands to the vehicle motors.'],
  ['Lessons learned', 'I learned that mechanical dimensions, sensor placement, software architecture, and control interfaces must be designed together. The project also reinforced the importance of safety margins, stable mounts, cable management, and staged simulation before real-world deployment.'],
  ['Future improvements', 'I would validate the AGV with combined static and dynamic obstacles, refine localization and route planning, complete the secure payload compartments, tune the safety thresholds, and expand testing in hospital-like environments with representative loads and users.'],
];
