export type Project = {
  slug: string;
  code: string;
  title: string;
  label: string;
  summary: string;
  description: string;
  year: string;
  status: string;
  category: string;
  tags: string[];
  accent: string;
  image?: string;
  gallery?: string[];
  galleryItems?: GalleryItem[];
  designItems?: GalleryItem[];
  caseSections?: Array<[string, string]>;
  external?: string;
  report?: string;
};

export type GalleryItem = {
  image: string;
  code: string;
  title: string;
  label: string;
  description: string;
};

export type Experience = {
  slug: string;
  period: string;
  role: string;
  organization: string;
  detail: string;
  tools: string;
  image?: string;
  progression?: string;
  galleryItems?: GalleryItem[];
};

export type EducationRecord = {
  period: string;
  qualification: string;
  institution: string;
  detail: string;
  galleryItems?: GalleryItem[];
};

export const profile = {
  name: 'Isameldin Ahmed',
  fullName: 'Isameldin Ahmed Hussein Ahmed',
  title: 'Mechatronics Engineering Graduate',
  location: 'Kuala Lumpur, Malaysia',
  email: 'eldeenisam@gmail.com',
  phone: '+60 11-3900 9572',
  linkedin: 'https://linkedin.com/in/isameldin',
  github: 'https://github.com/R3TR0S4M',
  website: 'https://isameldin.eldeenisam.workers.dev',
  tagline: 'I build, automate, and improve the things around me.',
  intro: 'I am a passionate mechatronics engineering graduate with experience in mechanical design and IoT systems development, plus hands-on academic work in robotics, automation, embedded systems, and control. I enjoy turning a practical problem into a system that I can test, understand, and improve.',
};

export const projects: Project[] = [
  { slug: 'fyp', code: 'FYP-01', title: 'EMG-Controlled Prosthetic Arm', label: 'FINAL YEAR PROJECT', summary: 'I developed a 3D-printed HACKberry prosthetic arm with EMG control, sensory feedback, safety responses, and an ESP32-based control system.', description: 'I developed a modified HACKberry prosthetic arm controlled by surface EMG signals. My Phase 2 system combines an ESP32, servo-driven movement, thermistor and piezoelectric sensing, vibration feedback, safety responses, and a web-based calibration dashboard.', year: '2026', status: 'Final year project', category: 'Embedded Systems', tags: ['ESP32', 'EMG', 'Sensors', 'Dashboard'], accent: 'red', image: '/images/projects/fyp/hackberry-platform.jpg', report: '/documents/isameldin-ahmed-fyp-phase-2-report.pdf', gallery: ['/images/projects/fyp-prosthetic-arm.jpg', '/images/projects/fyp-assembly.jpg', '/images/projects/fyp-testing.jpg'], galleryItems: [
    { image: '/images/projects/fyp/hackberry-platform.jpg', code: 'FYP-02', title: 'HACKberry arm platform', label: 'REFERENCE PLATFORM', description: 'I used the open-source HACKberry arm as the mechanical starting point, then adapted its platform with added wrist and elbow movement, EMG control, and sensory feedback.' },
    { image: '/images/projects/fyp/cad-side-view.png', code: 'FYP-03', title: 'Modified prosthetic arm CAD', label: 'MECHANICAL DESIGN', description: 'I arranged the adapted hand, wrist interface, and forearm casing around the servo-driven mechanism, wiring, and embedded electronics in this side-view CAD model.' },
    { image: '/images/projects/fyp/system-architecture.png', code: 'FYP-04', title: 'Updated system architecture', label: 'SYSTEM ARCHITECTURE', description: 'I mapped the signal path from muscle input and single-channel EMG acquisition through ESP32 sampling, signal processing, classification, control, sensing, calibration, actuation, and vibration feedback.' },
    { image: '/images/projects/fyp/emg-dashboard.png', code: 'FYP-05', title: 'EMGARM calibration dashboard', label: 'SOFTWARE INTERFACE', description: 'I brought the live EMG envelope, pulse features, curve shape, calibration values, and training states into one workspace for configuring prosthetic gestures.' },
    { image: '/images/projects/fyp/emg-test.png', code: 'FYP-06', title: 'Live EMG signal test', label: 'EXPERIMENTAL TESTING', description: 'I connected surface EMG electrodes during a live test and streamed muscle activation data to the dashboard for signal inspection and gesture classification.' },
    { image: '/images/projects/fyp/prototype.jpg', code: 'FYP-07', title: 'Integrated physical prototype', label: 'SYSTEM INTEGRATION', description: 'I assembled the 3D-printed hand, forearm casing, wrist module, and embedded hardware into a working physical prototype.' },
    { image: '/images/projects/fyp/emg-arm-bench-integration.jpg', code: 'FYP-08', title: 'Prototype electronics integration', label: 'SERVO / POWER / CONTROL', description: 'I connected the prosthetic hand to the bench electronics, showing the servo wiring, breadboard, power module, and control hardware used during prototype integration.' },
    { image: '/images/projects/fyp/distance-response.png', code: 'FYP-09', title: 'Distance response results', label: 'RESULTS / VALIDATION', description: 'I recorded the measured thumb-index distance across 30 trials to evaluate the prosthetic movement response during testing.' },
  ] },
  { slug: 'gdp', code: 'GDP-02', title: 'Automated Guided Vehicle for Hospitals', label: 'GROUP DESIGN PROJECT', summary: 'I designed a hospital logistics AGV to transport medical supplies and biohazard waste using ROS2 navigation, LiDAR, camera sensing, and a modular aluminium chassis.', description: 'I designed the AGV chassis and navigation hardware for a hospital logistics vehicle intended to carry medical supplies and biohazard waste. The report documents my SolidWorks chassis, suspension and sensor brackets, ROS2 navigation approach, LiDAR and camera integration, and Jetson and ESP32 control hardware.', year: '2026', status: 'Group design project', category: 'Robotics', tags: ['ROS2', 'LiDAR', 'SolidWorks', 'Jetson'], accent: 'olive', image: '/images/projects/gdp/agv-cover-platform.jpg', report: '/documents/gdp-report-agv-group.pdf', galleryItems: [
    { image: '/images/projects/gdp/chassis-frame.jpg', code: 'GDP-03', title: 'Fabricated AGV chassis frame', label: 'MECHANICAL STRUCTURE', description: 'I used aluminium extrusion to create a stable 120 cm by 100 cm chassis platform for the drive system, payload area, batteries, and navigation hardware.' },
    { image: '/images/projects/gdp/initial-frame-build.jpg', code: 'GDP-04', title: 'Initial frame build', label: 'PROTOTYPE ASSEMBLY', description: 'I translated the SolidWorks concept into a physical platform and established the mounting points used during later integration.' },
    { image: '/images/projects/gdp/chassis-progress.jpg', code: 'GDP-05', title: 'Chassis work in progress', label: 'PROTOTYPE DEVELOPMENT', description: 'I documented the AGV chassis during assembly, showing the aluminium frame, wheel modules, suspension struts, wiring, and front lighting before payload enclosure and final integration.' },
    { image: '/images/projects/gdp/lighting-assembly.jpg', code: 'GDP-06', title: 'Front lighting and sensor hardware', label: 'HARDWARE INTEGRATION', description: 'I mounted the lighting module and sensor support hardware to the aluminium frame for operation in indoor hospital environments.' },
    { image: '/images/projects/gdp/suspension-bracket.jpg', code: 'GDP-07', title: 'Suspension bracket implementation', label: 'FABRICATION DETAIL', description: 'I used a custom PLA+ bracket, M6 fasteners, and deliberate alignment to secure the suspension strut to the 45 by 45 mm extrusion and transfer loads during motion.' },
    { image: '/images/projects/gdp/lidar-bracket.jpg', code: 'GDP-08', title: 'LiDAR mounting solution', label: 'NAVIGATION HARDWARE', description: 'I positioned the Unitree 4D LiDAR above the chassis for a clear scanning view while preserving space for the camera and other front-mounted hardware.' },
    { image: '/images/projects/gdp/gazebo-simulation.jpg', code: 'GDP-09', title: 'Gazebo navigation simulation', label: 'ROS2 VALIDATION', description: 'I used Gazebo to test the navigation stack around static warehouse-style obstacles, using sensor data with global and local path planning before real-world deployment.' },
    { image: '/images/projects/gdp/electronics-layout.jpg', code: 'GDP-10', title: 'Integrated electronics layout', label: 'SYSTEM INTEGRATION', description: 'I recorded the placement of the battery, motor hubs, emergency stop, wiring, and LiDAR on the completed platform to support balanced integration and cable management.' },
  ], designItems: [
    { image: '/images/projects/gdp/payload-enclosure-cad.jpg', code: 'GDP-CAD-01', title: 'Payload enclosure concept', label: 'SOLIDWORKS / 3D DESIGN', description: 'I modelled the enclosure concept around the AGV frame to create a dedicated structure for carrying hospital supplies and biohazard waste.' },
    { image: '/images/projects/gdp/suspension-attachment-cad.jpg', code: 'GDP-CAD-02', title: 'Suspension frame attachment', label: 'SOLIDWORKS / 3D DESIGN', description: 'I designed the suspension attachment around the 45 by 45 mm aluminium profile so the strut could be aligned with the chassis and secured with fasteners.' },
    { image: '/images/projects/gdp/suspension-hole-cad.png', code: 'GDP-CAD-03', title: 'Suspension bracket detail', label: 'SOLIDWORKS / DETAIL VIEW', description: 'I used this CAD detail to position the suspension strut and transfer loads into the frame through the machined opening and mounting geometry.' },
    { image: '/images/projects/gdp/lidar-mount-cad.jpg', code: 'GDP-CAD-04', title: 'Unitree 4D LiDAR mount', label: 'SOLIDWORKS / NAVIGATION', description: 'I designed the LiDAR plate with the required mounting pattern and dimensions so the sensor could sit at a clear scanning height above the vehicle.' },
  ] },
  { slug: 'suspension-fea', code: 'FEA-03', title: 'Crankshaft FEA and Optimization', label: 'FINITE ELEMENT ANALYSIS', summary: 'I evaluated a crankshaft with modal, torsional, and model-reduction analysis, then compared material and geometry improvements for AMR use.', description: 'I used Altair analysis to study the vibration and torsional behaviour of a crankshaft intended for heavy-duty autonomous mobile robots. I examined natural frequencies, mode shapes, torsion rigidity, model reduction, and a possible 4340 steel optimization.', year: '2025', status: 'Completed academic project', category: 'Mechanical Design', tags: ['Altair', 'FEA', 'Modal Analysis', 'Optimization'], accent: 'olive', image: '/images/projects/fea/crankshaft-cover.jpg', caseSections: [
    ['Analysis focus', 'I prepared the crankshaft for finite element analysis and examined how its geometry responds to vibration and torsional loading. The report uses modal analysis to identify the natural frequencies and mode shapes that matter most for resonance and structural behaviour.'],
    ['Key findings', 'I identified the first natural frequency at 27.14 Hz and the second mode at 175 Hz. I also evaluated the crankshaft under a 200 Nm torque, reviewing stress concentration and torsional rigidity around the pulley end and main web regions.'],
    ['Design direction', 'I used the analysis results to compare practical improvement paths, including 4340 steel, larger fillet radii, web-thickness changes, shot peening, and nitriding. Model reduction helped me separate global rigid-body movement from internal deformation before making those recommendations.'],
  ], galleryItems: [
    { image: '/images/projects/fea/crankshaft-mesh.jpg', code: 'FEA-04', title: 'Crankshaft analysis model', label: 'FEA / MESH', description: 'I prepared the crankshaft model for finite element analysis and used the mesh as the basis for evaluating its dynamic response.' },
    { image: '/images/projects/fea/mode-1-response.jpg', code: 'FEA-05', title: 'Mode 1 response', label: 'MODAL ANALYSIS', description: 'I identified the first natural frequency at 27.14 Hz, representing the most critical global bending mode for resonance consideration.' },
    { image: '/images/projects/fea/mode-2-response.jpg', code: 'FEA-06', title: 'Mode 2 response', label: 'MODAL ANALYSIS', description: 'I compared the higher-order bending behaviour at 175 Hz and reviewed how the deformation was distributed across the crankshaft.' },
    { image: '/images/projects/fea/torsion-rigidity.jpg', code: 'FEA-07', title: 'Torsion rigidity analysis', label: 'TORSIONAL RESPONSE', description: 'I evaluated the crankshaft under a 200 Nm torque and reviewed the stress concentration near the pulley end.' },
    { image: '/images/projects/fea/model-reduction.png', code: 'FEA-08', title: 'Model reduction analysis', label: 'MODEL REDUCTION', description: 'I used model reduction to study the low-frequency global motion and separate rigid-body movement from internal deformation.' },
  ] },
  { slug: 'cam-lidar-mount', code: 'CAM-04', title: 'LiDAR Mount CAM and Toolpaths', label: 'SOLIDWORKS CAM / CNC', summary: 'I designed and prepared an aluminium LiDAR mounting plate for 3-axis CNC machining, then used topology results to reduce unnecessary mass.', description: 'I designed a LiDAR mounting plate for an autonomous mobile robot and simulated its manufacture using SolidWorks CAM. I defined the machine setup, coordinate system, stock, machining features, toolpaths, and a redesigned plate after topology optimization.', year: '2025', status: 'Completed academic project', category: 'Mechanical Design', tags: ['SolidWorks CAM', 'CNC', 'Toolpaths', 'Topology'], accent: 'khaki', image: '/images/projects/cam/lidar-mount-cover.jpg', caseSections: [
    ['Component design', 'I designed the LiDAR plate around a 105.12 by 75.85 by 11 mm envelope, with mounting holes, slots, and central features positioned around the sensor assembly and the functional requirements of the autonomous mobile robot.'],
    ['CAM preparation', 'I set up the SolidWorks CAM workflow for a 3-axis CNC process, defining the stock, coordinate system, machining features, tools, and toolpaths. I planned facing, drilling, pocketing, and contour operations so the component could be manufactured in a controlled sequence.'],
    ['Optimization and outcome', 'I used the topology study to identify where material could be removed while protecting the main load paths and stiffness. I then redesigned the aluminium 6061-T6 plate and checked the revised machining process against the lighter geometry.'],
  ], galleryItems: [
    { image: '/images/projects/cam/lidar-mount-drawing.png', code: 'CAM-05', title: 'LiDAR mount design', label: 'CAD / COMPONENT DESIGN', description: 'I defined the plate geometry, mounting holes, central features, and slots around the functional requirements of the LiDAR assembly.' },
    { image: '/images/projects/cam/topology-study.png', code: 'CAM-06', title: 'Topology study', label: 'DESIGN OPTIMIZATION', description: 'I used the topology study to identify areas where material could be removed while maintaining the critical load paths and stiffness of the plate.' },
    { image: '/images/projects/cam/redesigned-lidar-plate.jpg', code: 'CAM-07', title: 'Redesigned LiDAR plate', label: 'WEIGHT REDUCTION', description: 'I redesigned the plate around the topology results to improve its weight-to-strength balance before regenerating the machining process.' },
    { image: '/images/projects/cam/machined-lidar-plate.png', code: 'CAM-08', title: 'Machining simulation', label: 'SOLIDWORKS CAM / TOOLPATH', description: 'I verified the revised toolpath sequence for facing, drilling, pocketing, and contour operations on a 3-axis CNC setup.' },
  ] },
  { slug: 'machine-vision-mushroom-inspection', code: 'MVI-05', title: 'Mushroom Disease Inspection', label: 'MACHINE VISION / AI', summary: 'I built a mushroom inspection system that combines OpenCV disease detection, Roboflow and YOLOv8 inference, and a GUI for multiple inspection tasks.', description: 'I worked on a group machine-vision assignment focused on White Enoki mushroom inspection. My individual tasks covered traditional OpenCV classification of bacterial, fungal, and physiological disease, plus a Roboflow and YOLOv8 model for disease detection. I also helped integrate the inspection tools into a Tkinter GUI.', year: '2025', status: 'Completed academic project', category: 'Electronics', tags: ['OpenCV', 'YOLOv8', 'Roboflow', 'Python'], accent: 'red', image: '/images/projects/mvi/enoki-mushrooms-cover.jpg', caseSections: [
    ['Vision pipeline', 'I used grayscale conversion, thresholding, contour extraction, area, circularity, and aspect-ratio measurements to classify bacterial, fungal, and physiological disease patterns in White Enoki mushroom images. I also drew bounding boxes so the result could be inspected visually.'],
    ['AI disease detection', 'I prepared the Roboflow workflow and used YOLOv8 inference to detect disease regions, return class labels, and display confidence values. The report sets a 30% confidence threshold so the model can show useful results without hiding lower-confidence detections.'],
    ['Inspection interface', 'I helped integrate the separate inspection tasks into a Tkinter GUI. The interface supports model selection, camera or video input, disease detection, ripeness checks, distance measurement, and image segmentation so the different computer-vision methods can be tested from one workspace.'],
  ], galleryItems: [
    { image: '/images/projects/mvi/disease-classification.jpg', code: 'MVI-06', title: 'OpenCV disease classification', label: 'TRADITIONAL COMPUTER VISION', description: 'I classified bacterial, fungal, and physiological disease using contour area, circularity, aspect ratio, thresholding, and bounding boxes.' },
    { image: '/images/projects/mvi/roboflow-disease-results.png', code: 'MVI-07', title: 'Roboflow disease results', label: 'YOLOV8 / AI INFERENCE', description: 'I trained and deployed a Roboflow and YOLOv8 model to identify disease regions and return class labels with confidence values.' },
    { image: '/images/projects/mvi/inspection-gui.png', code: 'MVI-08', title: 'Inspection GUI', label: 'PYTHON / TKINTER', description: 'I integrated the inspection options into a Tkinter interface so a user can choose a model, camera or video input, and the required analysis task.' },
    { image: '/images/projects/mvi/inspection-flowchart.png', code: 'MVI-09', title: 'Integrated inspection flow', label: 'SYSTEM INTEGRATION', description: 'I mapped the flow from model selection and input choice through OpenCV or Roboflow processing and the final inspection result.' },
    { image: '/images/projects/mvi/gui-disease-results.jpg', code: 'MVI-10', title: 'GUI disease inspection result', label: 'RESULTS', description: 'I tested the integrated interface with disease inspection output and bounding-box labels over the mushroom images.' },
    { image: '/images/projects/mvi/image-segmentation.jpg', code: 'MVI-11', title: 'Image segmentation', label: 'ADDITIONAL INSPECTION TASK', description: 'I added image segmentation as one of the supporting inspection modes available through the integrated interface.' },
    { image: '/images/projects/mvi/distance-detection.jpg', code: 'MVI-12', title: 'Distance detection', label: 'ADDITIONAL INSPECTION TASK', description: 'I added distance measurement as another inspection mode, showing the measured object span on the processed frame.' },
  ] },
  { slug: 'industrial-automation', code: 'PLC-06', title: 'Automated Sortation and Stamping System', label: 'ELECTRO-PNEUMATIC AUTOMATION', summary: 'I built and simulated a conveyor system that sorts objects by height and stamps accepted items using sensors, relays, motors, and pneumatic cylinders.', description: 'I developed an electro-pneumatic quality-control system around a conveyor, two double-action cylinders, infrared sizing sensors, limit switches, relays, and a stamping mechanism. The project was implemented in Automation Studio and demonstrated physically as a working prototype.', year: '2024', status: 'Completed academic project', category: 'Automation', tags: ['Pneumatics', 'Sensors', 'Automation Studio', 'Conveyors'], accent: 'khaki', image: '/images/projects/industrial-automation/physical-sortation-system.jpg', caseSections: [
    ['System objective', 'I designed the system to identify objects by height, reject items outside the accepted range, and stamp the items that reached the correct position. This gave me a practical quality-control application for studying electro-pneumatic automation.'],
    ['Control and hardware', 'I used five infrared sensors for object sizing, two electric limit switches for the inking and stamping positions, two 12 V DC motors for the conveyor and ball-screw movement, and two double-action pneumatic cylinders for sorting and stamping. Relay modules connected the 5 V sensor signals to the 24 V control circuit.'],
    ['Performance and improvements', 'The prototype and Automation Studio model successfully sorted objects by height, stopped the conveyor at the stamping position, completed the stamping motion, and restarted the conveyor. I also identified improvements including an emergency stop and reset, an in-progress indicator, better cylinder-dimension planning, and additional sensors for different object heights.'],
  ], galleryItems: [
    { image: '/images/projects/industrial-automation/physical-sortation-system.jpg', code: 'PLC-07', title: 'Physical sortation prototype', label: 'INDUSTRIAL AUTOMATION / BUILD', description: 'I assembled the conveyor, stamping head, pneumatic hardware, control wiring, and sorting path into a physical prototype for testing.' },
    { image: '/images/projects/industrial-automation/control-circuit.jpg', code: 'PLC-08', title: 'Electro-pneumatic control circuit', label: 'AUTOMATION STUDIO / CONTROL', description: 'I mapped the infrared sensors, relays, switches, motors, and cylinder outputs into a control circuit that coordinates sizing, sorting, and stamping.' },
    { image: '/images/projects/industrial-automation/sortation-prototype.jpg', code: 'PLC-09', title: 'Prototype integration view', label: 'SYSTEM INTEGRATION', description: 'I used the integrated build to examine how the conveyor, lead screw, stamping position, sensor wiring, and pneumatic actuators work together.' },
  ] },
  { slug: 'smart-city-health', code: 'IOT-07', title: 'Smart City Health Monitoring', label: 'IOT / MONITORING', summary: 'I developed an academic IoT system for sensor data acquisition, remote monitoring, and pollution control concepts.', description: 'I developed an IoT smart city health monitoring system focused on collecting sensor data, supporting remote monitoring, and exploring pollution control responses.', year: 'Academic project', status: 'Completed academic work', category: 'Electronics', tags: ['IoT', 'Sensors', 'Monitoring'], accent: 'red' },
  { slug: 'robot-mapping', code: 'ROB-08', title: 'Boe-Bot Line Following and Obstacle Avoidance', label: 'ARDUINO / MOBILE ROBOTICS', summary: 'I programmed a Boe-Bot to follow a marked route, handle junctions, and stop safely when it detected an obstacle.', description: 'I built a small autonomous robot around an Arduino, two continuous-rotation servos, five infrared sensors, and an ultrasonic distance sensor. My control logic combines line-following patterns with junction handling and a safety stop for obstacles.', year: '2024', status: 'Completed academic project', category: 'Robotics', tags: ['Arduino', 'Infrared Sensors', 'Ultrasonic', 'Line Following'], accent: 'olive', image: '/images/projects/boebot/boebot-platform.jpg', caseSections: [
    ['Control architecture', 'I used five infrared sensors on digital inputs to read the line position and two continuous-rotation servos to drive the wheels. An ultrasonic sensor monitored the path ahead so the robot could stop when an object came within 5 cm.'],
    ['Navigation logic', 'I mapped the sensor patterns to forward, left, and right corrections, then added a junction counter so the robot could recognise the three junctions in its route and make the required turns.'],
    ['Validation and reflection', 'I tested the route as a complete pathway and recorded a completion time of under 40 seconds. The report also helped me identify practical limits such as servo variation, battery condition, line width, and the need to tune speed and sensor thresholds.'],
  ], galleryItems: [
    { image: '/images/projects/boebot/boebot-platform.jpg', code: 'ROB-09', title: 'Boe-Bot control setup', label: 'ARDUINO / ROBOTICS', description: 'I used the Boe-Bot platform to combine Arduino control, continuous-rotation servos, line sensors, and ultrasonic obstacle detection.' },
    { image: '/images/projects/boebot/boebot-obstacle-test.jpg', code: 'ROB-10', title: 'Obstacle response test', label: 'ULTRASONIC SAFETY', description: 'I tested the robot stopping when an obstacle was placed in front of the platform, using the ultrasonic sensor as the safety trigger.' },
    { image: '/images/projects/boebot/boebot-route-test.jpg', code: 'ROB-11', title: 'Line-following route test', label: 'LINE FOLLOWING / VALIDATION', description: 'I tested the Boe-Bot on the marked route and used its sensor pattern and junction logic to keep it moving through the pathway.' },
  ] },
  { slug: 'abb-pick-and-place', code: 'ABB-09', title: 'ABB Robot Pick and Place', label: 'ABB IRB 120 / RAPID', summary: 'I programmed an ABB IRB 120 to pick pegs and palletise them into the letter G using fixed positions and coordinate offsets.', description: 'I programmed an ABB IRB 120 robotic arm for a pick-and-place and palletising task. I used the teach pendant, fixed positions, RAPID motion instructions, and X/Y offsets to place pegs accurately into the assigned letter G pattern.', year: '2024', status: 'Completed academic project', category: 'Robotics', tags: ['ABB IRB 120', 'RAPID', 'Palletising', 'Teach Pendant'], accent: 'red', image: '/images/projects/abb-robot/abb-irb-120.png', caseSections: [
    ['Task and setup', 'I programmed the six-axis ABB IRB 120 to pick pegs from one pallet and place them in a second pallet. My assigned output was the letter G, so the placement order had to create a repeatable shape without damaging the pegs or gripper.'],
    ['Program design', 'I established safe and working positions through teach-pendant testing, then reused them with Movel and Fine instructions. I used 25 mm Y-axis offsets and 30 mm X-axis offsets to build the rows and final inner section of the letter.'],
    ['Result and limits', 'The arm produced the required letter accurately and repeatedly at a programmed velocity of 200. I also documented the conditions that affect repeatability: calibration, pallet alignment, consistent grid depth, and a clear workspace without external resistance.'],
  ], galleryItems: [
    { image: '/images/projects/abb-robot/abb-irb-120.png', code: 'ABB-10', title: 'ABB IRB 120 robot', label: 'ROBOTIC ARM / PLATFORM', description: 'I used the six-axis ABB IRB 120 platform and teach pendant to establish the fixed pick, safe, and place positions for the palletising sequence.' },
    { image: '/images/projects/abb-robot/abb-pallet.jpg', code: 'ABB-11', title: 'Peg pallet arrangement', label: 'PALLETISING / SETUP', description: 'I planned the peg rows and measured the X/Y offsets required to build the assigned letter pattern on the destination pallet.' },
    { image: '/images/projects/abb-robot/abb-result.jpg', code: 'ABB-12', title: 'Resultant letter G', label: 'PALLETISING / VALIDATION', description: 'I validated the RAPID program by placing the pegs in sequence and producing the assigned letter G on the destination pallet.' },
  ] },
  { slug: 'train-scheduling', code: 'PY-09', title: 'Malayan Railway Scheduling System', label: 'PYTHON / PROGRAMMING', summary: 'I built a Python-based timetable and route-management system for Malayan Railway Limited.', description: 'I built a Python system with separate passenger and administrator roles. Passengers can view routes and stop schedules, while administrators can authenticate, add routes, edit stops, delete services, and maintain the timetable data.', year: '2022', status: 'Completed academic project', category: 'Programming', tags: ['Python', 'Scheduling', 'CSV Files'], accent: 'khaki', image: '/images/projects/python/train-schedule-cover.png', caseSections: [
    ['System roles', 'I separated the application into passenger and administrator workflows. Passengers can view the available timetable, while administrators authenticate before they can manage routes and stop information.'],
    ['Route management', 'I used functions and CSV-style text files to display routes, view individual train stops, add new services, edit stop data, and delete routes. The program returns users to the correct menu after each operation and handles invalid choices through repeated prompts.'],
    ['Reflection', 'I learned how to structure a multi-file Python application around reusable functions, lists, loops, file handling, and a menu-driven interface. The report also helped me recognise that a more complex railway system would benefit from a proper database and stronger validation.'],
  ], galleryItems: [
    { image: '/images/projects/python/train-schedule-cover.png', code: 'PY-10', title: 'Route and timetable output', label: 'PYTHON / SYSTEM OUTPUT', description: 'I used this timetable view to show route IDs, origin and destination stations, departure times, arrival times, and the available administrator actions.' },
    { image: '/images/projects/python/train-schedule-login.png', code: 'PY-11', title: 'Role-based entry point', label: 'PYTHON / USER FLOW', description: 'I created a main menu that directs passengers to timetable viewing and administrators to an authenticated route-management workflow.' },
    { image: '/images/projects/python/train-schedule-admin.png', code: 'PY-12', title: 'Administrator route control', label: 'PYTHON / CRUD OPERATIONS', description: 'I used administrator options to view, add, edit, and delete train routes while keeping the timetable file updated.' },
  ] },
  { slug: 'leave-management', code: 'C-10', title: 'APU Leave Management System', label: 'C / PROGRAMMING', summary: 'I developed a C-based leave management system with separate staff, supervisor, and administrator access.', description: 'I developed a C system to manage employee leave requests for a university environment. Staff can apply for leave and check its status, supervisors can review team requests, and administrators can add users, search staff records, and view the wider staff database.', year: '2023', status: 'Completed academic project', category: 'Programming', tags: ['C', 'Data Structures', 'Access Control'], accent: 'red', image: '/images/projects/leave-management/leave-supervisor-cover.png', caseSections: [
    ['Role-based workflow', 'I designed three user roles with different responsibilities. Staff submit and check leave requests, supervisors review and update team statuses, and administrators manage user records and staff searches.'],
    ['Records and validation', 'I used C structures, text-file storage, string parsing, and file updates to manage staff details, login records, leave requests, and status changes. I also defined rules for duplicate applications, past dates, supervisor self-approval, and active leave periods.'],
    ['Technical reflection', 'I learned how to organise a larger C program with functions, structs, pointers, loops, and file operations. The report also identifies the limits of building complex access control and data management without the built-in data structures and object-oriented features available in other languages.'],
  ], galleryItems: [
    { image: '/images/projects/leave-management/leave-org-chart.png', code: 'C-11', title: 'Organisation and access model', label: 'C / SYSTEM DESIGN', description: 'I mapped the supervisor, administrator, and staff relationships that control which leave-management actions each role can perform.' },
    { image: '/images/projects/leave-management/leave-supervisor-cover.png', code: 'C-12', title: 'Supervisor leave review', label: 'C / SUPERVISOR WORKFLOW', description: 'I implemented a supervisor workflow for viewing team leave requests and updating a request status.' },
    { image: '/images/projects/leave-management/leave-admin-records.png', code: 'C-13', title: 'Administrator staff records', label: 'C / ADMIN WORKFLOW', description: 'I built an administrator view for adding users, searching staff, and displaying staff records with departments, leave balances, and user types.' },
  ] },
  { slug: 'solidworks-submarine', code: 'CAD-11', title: 'Submarine Design', label: 'SOLIDWORKS / CAD', summary: 'I completed a SolidWorks submarine design study covering the shell, storage, electrical box, and access door.', description: 'I designed a submarine concept around safety, speed, material selection, water mobility, and practical manufacture. My individual work focused on the section joining the main fuselage and tail, together with internal components including the storage shelf, electrical box, and electrical-box door.', year: '2022', status: 'Completed academic project', category: 'Mechanical Design', tags: ['SolidWorks', '3D CAD', 'Sheet Metal'], accent: 'olive', image: '/images/projects/submarine/submarine-assembly.png', caseSections: [
    ['Design objectives', 'I designed the submarine to carry a person safely, travel at speed on the surface of the water, resist changing climatic and water conditions, and reduce the effect of water resistance through a practical body shape.'],
    ['Component design', 'I modelled the shell with lofted bases and a thickened surface, then designed a sheet-metal storage shelf with dividers. I also developed an electrical box with ventilation louvers, a lower vent, embossed fasteners, and a hinged door with a grip opening.'],
    ['Design decisions', 'I prioritised functionality, manufacturability, cooling, access, and cost. The tapered shell improves water mobility and reduces complexity, while the electrical-box ventilation supports cooling and the simple storage dividers keep fabrication practical.'],
  ], galleryItems: [
    { image: '/images/projects/submarine/submarine-shell-reference.jpg', code: 'CAD-12', title: 'Submarine shell reference', label: 'DESIGN CONCEPT', description: 'I used the shell reference to guide the form of the fuselage and the structural direction of my SolidWorks model.' },
    { image: '/images/projects/submarine/electrical-box.png', code: 'CAD-13', title: 'Ventilated electrical box', label: 'SOLIDWORKS / SHEET METAL', description: 'I designed the electrical box with side louvers, a lower vent, countersunk details, and a hinged enclosure for safer component access and cooling.' },
    { image: '/images/projects/submarine/submarine-assembly.png', code: 'CAD-14', title: 'Electrical box assembly', label: 'SOLIDWORKS / ASSEMBLY', description: 'I used the assembly view to check the relationship between the enclosure, vents, hinges, and removable door.' },
  ] },
  { slug: 'vacuum-pick-and-place', code: 'PLC-12', title: 'Electro-Pneumatic Pick and Place', label: 'OMRON PLC / AUTOMATION', summary: 'I worked on an electro-pneumatic vacuum pick-and-place device controlled with an Omron PLC.', description: 'I worked on an electro-pneumatic vacuum pick-and-place device using an Omron PLC. Supporting photos and sequence evidence will be added when I have the project material ready.', year: 'Academic experience', status: 'Project record in progress', category: 'Automation', tags: ['Omron PLC', 'Pneumatics', 'Pick and Place'], accent: 'khaki' },
  { slug: 'digital-circuits', code: 'ELEC-13', title: 'ALU and 7-Segment Display Circuit', label: 'DIGITAL LOGIC / CIRCUIT DESIGN', summary: 'I designed an ALU-style digital circuit that simplifies Boolean logic and displays calculated values across four 7-segment displays.', description: 'I designed and simulated a digital logic system around an ALU task. I used truth tables, Karnaugh maps, Boolean expressions, logic gates, BCD-to-7-segment conversion, and a control unit to switch between group members’ circuit outputs.', year: '2023', status: 'Completed academic project', category: 'Electronics', tags: ['Logic Gates', 'Karnaugh Maps', '7-Segment', 'Digital Design'], accent: 'red', image: '/images/projects/digital/alu-cover.png', caseSections: [
    ['ALU design brief', 'I translated binary inputs and the assigned equations into predictable digital outputs. Because the combined group design required values to be displayed clearly, I planned the circuit around four BCD-to-7-segment converters.'],
    ['Logic implementation', 'I simplified the Boolean expressions with truth tables and Karnaugh maps, then implemented the resulting logic with gates. I also considered a multiplexer or demultiplexer-based control approach so the group circuits could share the display path.'],
    ['Simulation and reflection', 'I refined the circuit in simulation to reduce unnecessary components while keeping the output readable and repeatable. The project strengthened my understanding of logic simplification, BCD conversion, display driving, and practical digital-system planning.'],
  ], galleryItems: [
    { image: '/images/projects/digital/alu-cover.png', code: 'ELEC-14', title: 'BCD display circuit', label: 'DIGITAL LOGIC / OUTPUT', description: 'I connected the binary output stage to BCD-to-7-segment converters so the calculated values could be read across the display digits.' },
    { image: '/images/projects/digital/alu-system.png', code: 'ELEC-15', title: 'ALU system architecture', label: 'LOGIC DESIGN / SYSTEM CONTROL', description: 'I mapped the relationship between the individual circuits, the group control method, the converters, and the final display outputs.' },
    { image: '/images/projects/digital/alu-display.png', code: 'ELEC-16', title: 'Multi-display output', label: 'SIMULATION / VALIDATION', description: 'I checked the simulated wiring for the four-display output and used the visible digits to confirm that the circuit produced the intended BCD values.' },
  ] },
  { slug: 'analogue-bjt-amplifier', code: 'AN-14', title: 'Multistage BJT Amplifier', label: 'ANALOGUE ELECTRONICS / SPICE', summary: 'I designed and simulated a multistage BJT amplifier, then checked its gain, cutoff frequencies, and DC operating points.', description: 'I designed a multistage bipolar-junction-transistor amplifier and used AC, DC, and transient analysis to evaluate its behaviour. My simulation reached a gain of 37.6 dB, a lower cutoff frequency of 128.7 Hz, and an upper cutoff frequency of 4.07 MHz.', year: '2024', status: 'Completed academic project', category: 'Electronics', tags: ['BJT', 'Analog Electronics', 'Gain', 'Frequency Response'], accent: 'khaki', image: '/images/projects/analogue/analog-circuit.png', caseSections: [
    ['Circuit design', 'I selected the BJT configuration and component values to amplify a weak input signal while keeping the stages stable and practical. I worked through the biasing and DC calculations before validating the circuit in simulation.'],
    ['Frequency response', 'I used AC analysis to examine how the gain changed across frequency. The simulated response produced a lower cutoff frequency of 128.7 Hz, an upper cutoff frequency of 4.07 MHz, and a midband gain of 37.6 dB.'],
    ['Reflection', 'I compared the DC operating points, AC response, and transient behaviour to check whether the circuit performed the intended amplification task. The work reinforced how transistor biasing, coupling, loading, and bandwidth interact in a multistage design.'],
  ], galleryItems: [
    { image: '/images/projects/analogue/analog-circuit.png', code: 'AN-15', title: 'Multistage amplifier circuit', label: 'BJT / CIRCUIT DESIGN', description: 'I assembled the multistage BJT circuit and established the component relationships used for the DC and AC analyses.' },
    { image: '/images/projects/analogue/analog-results.png', code: 'AN-16', title: 'AC analysis results', label: 'SPICE / FREQUENCY RESPONSE', description: 'I used the simulated response to read the gain and cutoff frequencies and compare the amplifier against the design target.' },
    { image: '/images/projects/analogue/analog-bench.jpg', code: 'AN-17', title: 'Physical electronics test', label: 'HARDWARE / VALIDATION', description: 'I connected the amplifier hardware on the bench and compared the practical signal behaviour with the simulated response.' },
  ] },
  { slug: 'matlab-op-amp-simulator', code: 'MATLAB-15', title: 'MATLAB Op-Amp Simulator', label: 'MATLAB APP DESIGNER', summary: 'I built a MATLAB App Designer simulator for operational-amplifier modes, input validation, plots, and protected data export.', description: 'I built a user-facing op-amp simulator in MATLAB App Designer. The application supports multiple operating modes, accepts numerical inputs, produces calculated outputs and graphs, handles invalid entries, saves screenshots, and exports password-protected data.', year: '2023', status: 'Completed academic project', category: 'Programming', tags: ['MATLAB', 'App Designer', 'Op-Amps', 'Simulation'], accent: 'olive', image: '/images/projects/matlab/matlab-cover.jpg', caseSections: [
    ['Simulation purpose', 'I created the simulator to make operational-amplifier calculations easier to explore through a single interface. The user can select an operating mode, enter positive numerical values, and view the resulting output without rebuilding the circuit manually.'],
    ['Application design', 'I used MATLAB App Designer callbacks, input validation, plots, help content, feedback access, screenshot capture, and export controls to turn the calculations into a more usable engineering tool.'],
    ['Results and reflection', 'I tested all three modes with different inputs and compared the outputs with traditional calculations. The report records accurate numerical results, correct amplitude graphs, error handling for invalid input, and password-protected data export.'],
  ], galleryItems: [
    { image: '/images/projects/matlab/matlab-cover.jpg', code: 'MATLAB-16', title: 'Op-amp simulator interface', label: 'MATLAB / APP DESIGNER', description: 'I brought the op-amp modes, input fields, calculated outputs, and graph area into one MATLAB App Designer interface.' },
    { image: '/images/projects/matlab/matlab-dual-opamp.png', code: 'MATLAB-17', title: 'Multi-mode simulation', label: 'MATLAB / SIMULATION', description: 'I used the interface to test more than one op-amp arrangement and compare the calculated response with the plotted signal.' },
    { image: '/images/projects/matlab/matlab-export-dialog.png', code: 'MATLAB-18', title: 'Protected data export', label: 'MATLAB / USER WORKFLOW', description: 'I added an export workflow that asks for a file name and password before saving the simulator data.' },
  ] },
  { slug: 'soft-drink-production', code: 'LABVIEW-14', title: 'Soft Drink Production System', label: 'LABVIEW / PROCESS', summary: 'I studied an automated soft drink production process using LabVIEW.', description: 'I designed a soft drink production system using LabVIEW. Supporting process-flow visuals and HMI evidence will be added when I have the project material ready.', year: 'Academic experience', status: 'Project record in progress', category: 'Programming', tags: ['LabVIEW', 'Process Control', 'HMI'], accent: 'olive' },
];

export const experience: Experience[] = [
  { slug: 'mechatronics-engineering-internship', period: 'MAR - SEP 2026', role: 'Mechatronics Engineering Intern', organization: 'Ambani Consortium Group (M) Sdn. Bhd.', detail: 'I designed brackets and technical drawings for generator housings, tested an LTE module for remote generator monitoring and control, applied DFM and Poka-Yoke principles, and supported technical coordination and client engagement for the 2025 Invest Zambia International Conference.', tools: 'SolidWorks / LTE / IoT Monitoring / DFM / Poka-Yoke / ISO 9001, 14001, 45001', image: '/images/experience/internship-team.jpg' },
  { slug: 'apu-senior-engineering-technical-assistant', period: 'DEC 2022 - JUL 2026', role: 'Senior Engineering Technical Assistant', organization: 'Asia Pacific University', progression: 'Promoted from Engineering Technical Assistant in December 2024', detail: 'I progressed from maintaining laboratory equipment to leading a team of lab assistants while supporting 20 to 50 students per semester across engineering lab sessions. I guided students with 3D printers, oscilloscopes, robotic arms, PLC units, and digital and analogue signal training kits.', tools: '3D Printing / Oscilloscopes / Robotic Arms / PLCs / Sensor Calibration / Team Leadership', galleryItems: [
    { image: '/images/experience/technical-assistant-lab.jpg', code: 'EXP-TECH-01', title: 'Supporting practical engineering sessions', label: 'LABORATORY SUPPORT', description: 'I worked alongside the engineering support team in an active laboratory environment, preparing equipment and helping practical sessions run safely and smoothly.' },
    { image: '/images/experience/technical-assistant-soldering.jpg', code: 'EXP-TECH-02', title: 'Soldering and fabrication bench work', label: 'ELECTRONICS / FABRICATION', description: 'I used the fabrication bench to inspect and work on small electronic assemblies, applying careful hand skills during equipment preparation and maintenance.' },
    { image: '/images/experience/technical-assistant-3d-printing.jpg', code: 'EXP-TECH-03', title: '3D-printing and hardware setup', label: '3D PRINTING / EMBEDDED HARDWARE', description: 'I supported 3D-printing and embedded-hardware activities by checking the printer setup, control computer, and connected electronics before practical use.' },
    { image: '/images/experience/technical-assistant-lidar-cad.jpg', code: 'EXP-TECH-04', title: 'Reviewing a LiDAR-frame CAD model', label: 'SOLIDWORKS / CAD REVIEW', description: 'I reviewed a LiDAR-frame component in SolidWorks, connecting the digital model to the practical mounting and fabrication requirements of an engineering system.' },
    { image: '/images/experience/technical-assistant-fabrication.jpg', code: 'EXP-TECH-05', title: 'Supporting workshop fabrication', label: 'WORKSHOP / FABRICATION', description: 'I worked around the fabrication area and its cutting, welding, and extraction equipment while supporting practical workshop preparation and engineering builds.' },
  ] },
  { slug: 'imeche-head-of-public-relations', period: 'AUG 2024 - MAY 2026', role: 'Head of Public Relations', organization: 'Institution of Mechanical Engineers, APU Student Section', detail: 'I led communications, built industry partnerships, invited speakers, spoke at events, and helped organise more than 20 workshops, competitions, and events for the student section.', tools: 'Public Relations / Industry Engagement / Event Management / Communications' },
];

export const education: EducationRecord[] = [
  { period: 'JUN 2022 - JUN 2026', qualification: 'Bachelor of Mechatronic Engineering with Honours', institution: 'Asia Pacific University', detail: 'I completed the dual DMU Degree Programme with Second Class Upper Division, including the De Montfort University award from Leicester.', galleryItems: [
    { image: '/images/education/apu-campus-atrium.jpg', code: 'EDU-APU-01', title: 'Life across the APU campus', label: 'CAMPUS / COMMUNITY', description: 'I studied in an international campus environment where engineering learning, student activities, and a diverse community came together.' },
    { image: '/images/education/apu-laboratory-team.jpg', code: 'EDU-APU-02', title: 'Engineering laboratory team', label: 'ENGINEERING / COLLABORATION', description: 'I worked with classmates and laboratory colleagues in practical engineering spaces, building the teamwork and communication needed for hands-on projects.' },
    { image: '/images/education/apu-engineering-community.jpg', code: 'EDU-APU-03', title: 'Engineering community', label: 'STUDENT COMMUNITY', description: 'I was part of a broad engineering community that brought together students, technical staff, and academic teams across different disciplines.' },
    { image: '/images/education/apu-classroom-session.jpg', code: 'EDU-APU-04', title: 'Learning through technical sessions', label: 'ACADEMIC / PRESENTATION', description: 'I developed my technical understanding through structured teaching, demonstrations, group work, and presentations throughout the degree.' },
    { image: '/images/education/apu-robotics-demonstration.jpg', code: 'EDU-APU-05', title: 'Robotics in the learning environment', label: 'ROBOTICS / PRACTICAL LEARNING', description: 'I connected classroom engineering principles to working robotic systems and demonstrations, reinforcing the practical side of my mechatronics education.' },
    { image: '/images/education/apu-logo.jpg', code: 'EDU-APU-06', title: 'Asia Pacific University', label: 'INSTITUTION / DEGREE', description: 'I completed my Bachelor of Mechatronic Engineering with Honours at Asia Pacific University through the dual DMU Degree Programme.' },
  ] },
  { period: 'JAN 2020 - NOV 2021', qualification: 'A Levels', institution: 'LICEF School, Lusaka, Zambia', detail: 'I achieved A in Physics, B in Chemistry, and B in Mathematics, and I graduated as high school valedictorian.' },
];

export const certificates = ['MATLAB Onramp', 'Simulink Onramp', 'Control Design Onramp with Simulink', 'Introduction to IoT', 'Python', 'C', 'Lean Six Sigma White Belt'];
export const skills = [
  { label: 'Programming and embedded systems', items: 'C, Python, MATLAB, Arduino, ESP32, machine vision, ROS2' },
  { label: 'Circuit design and CAD', items: 'Digital circuit design, SOLIDWORKS, Fusion 360, 2D engineering drawings, 3D printing' },
  { label: 'Automation and controls', items: 'PLC programming and control, stepper and servo motor control, sensor integration and calibration' },
  { label: 'Simulation and tools', items: 'Simulink, ABB RobotStudio, LabVIEW, Automation Studio, CX Programmer, LTspice, Multisim, Altair' },
];
export const awards = ['High School Valedictorian, LICEF Secondary School, Lusaka, Zambia', 'Al-Khayyam Mathematics Award, LICEF Secondary School, Lusaka, Zambia'];

export const fypSections = [
  ['Project overview', 'I adapted the open-source HACKberry prosthetic arm design and modified it to add EMG muscle-signal control for hand movement. My build combines an ESP32, sensor feedback, haptic vibration, safety responses, and an online dashboard.'],
  ['Problem statement', 'I identified that many prosthetic arms remain out of reach because of high purchase, maintenance, and rehabilitation costs. Lower-cost alternatives can provide limited movement and little or no sensory feedback, reducing their usefulness in daily activities.'],
  ['Aim', 'I aimed to develop a 3D-printed prosthetic arm controlled by electromyography signals that also provides environmental feedback through integrated sensors.'],
  ['Objectives', 'I set out to process EMG signals to control the five fingers, palm, and elbow with a target accuracy of at least 70%, develop feedback for surface roughness and temperature, adapt an existing arm into a low-cost 3D-printed system, and evaluate movement accuracy and task success.'],
  ['Research justification', 'I combined 3D printing, embedded control, and sensory feedback to explore a more affordable and adaptable assistive device. I used personalised EMG calibration to make the system more intuitive while reducing dependence on expensive proprietary hardware.'],
  ['My role and responsibilities', 'I adapted and 3D-printed the HACKberry design, modified the arm, integrated the ESP32 and sensors, developed the control and dashboard functions, and tested and improved the muscle-signal response.'],
  ['System design', 'I used the ESP32 as the central controller for single-channel EMG acquisition, signal conditioning, feature extraction, movement classification, actuator control, and sensor data. I connected a Wi-Fi dashboard for calibration, while piezoelectric sensing, a vibration motor, and a thermistor provided texture feedback and heat protection.'],
  ['Methodology', 'I followed a design, build, calibrate, test, and refine cycle. I filtered, rectified, smoothed, and mapped EMG signals to movement thresholds before integrating the mechanical system, actuator mounts, sensing hardware, and dashboard.'],
  ['Design changes', 'I used a single EMG channel to reduce setup complexity and processing load. I stored user-specific calibration values in ESP32 non-volatile memory and added an active wrist mechanism and integrated elbow structure to improve movement range and load distribution.'],
  ['Hardware and software', 'I used the HACKberry prosthetic-arm design, 3D-printed parts, an ESP32 microcontroller, EMG input, thermistors, pressure sensors, vibration feedback, analogue signal conditioning, digital signal processing, and a web-based dashboard.'],
  ['Technical specifications', 'I used seven servo motors for actuation, an ESP32 for embedded processing, surface EMG electrodes, PLA and PETG printed parts, a piezoelectric sensor, an NTC thermistor, and a vibration motor. My report estimates the component cost at RM546.'],
  ['Development process', 'I started from an open-source arm design, modified the mechanical structure, integrated control electronics and sensing, connected the dashboard, and refined the control response through testing.'],
  ['Testing and results', 'I tested EMG-to-distance mapping, servo response latency, power consumption, grip repeatability, and piezoelectric texture sensing. My report records control accuracy above 90% across the tested EMG states, internal response latency of 20 to 68 ms, and fingertip gaps from 1.5 to 2.4 mm across five repeated grips.'],
  ['Challenges and solutions', 'I reduced signal noise with high-pass, notch, and low-pass filtering, followed by user calibration. I addressed mechanical backlash and printed-part alignment through servo calibration, tendon adjustment, and reinforced components.'],
  ['Key achievements', 'I delivered a standalone ESP32-based prototype with seven controllable degrees of freedom across the fingers, wrist, and elbow. My system combines personalised EMG control, web calibration, texture feedback, heat protection, vibration feedback, and local storage of user parameters.'],
  ['Sustainability and accessibility', 'I used open-source foundations, additive manufacturing, modular parts, and commercially available electronics to support repair and adaptation. The low estimated component cost is intended to reduce barriers to assistive technology, while I also recognised the need to manage electronic waste and design for disassembly.'],
  ['Limitations', 'I found that the single-channel EMG system limits simultaneous movement commands and requires recalibration for different users. Texture sensing can be affected by mounting position and vibration, and my controlled validation setting requires wider clinical testing.'],
  ['Lessons learned', 'I learned that mechanical design, analogue signal conditioning, embedded programming, sensor integration, control logic, and user-facing software must work together. The project reinforced the importance of calibration, repeatable testing, safe limits, and designing around real user variability.'],
  ['Future improvements', 'I would investigate multi-channel EMG with richer classification, closed-loop grip-force sensing, lighter actuators, improved power management, and broader trials with clinical representatives and diverse users.'],
];

export const gdpSections = [
  ['Project overview', 'I worked on a smart automated guided vehicle for hospital logistics. The intended use is secure transport of medical supplies and biohazard waste while reducing manual handling and supporting safer movement through hospital environments.'],
  ['Problem statement', 'I identified that hospital staff spend significant time moving food, medicine, equipment, and waste. Manual transport creates physical strain, takes staff away from patient care, can introduce delivery errors, and becomes harder to scale across larger hospital buildings.'],
  ['Aim and objectives', 'I aimed to design and build a working prototype of a smart AGV for secure hospital transport. The objectives were to develop autonomous navigation, implement secure dual-payload compartments using RFID authentication, design an automatic obstacle-stop safety system, and test the AGV implementation.'],
  ['Team members', 'I worked with Ayser Amir Kamil Mohamed, Badr Bassam Hassan Albdulmajeed, and Rayan Khalid Mubarak Al Yaquobi under the supervision of Dr. Sathish Kumar Selvaperumal.'],
  ['My individual contribution', 'Isameldin Ahmed focused on the AGV design and navigation section. This included SolidWorks schematics for the chassis, suspension bracket, LiDAR mount, and camera mount, together with the ROS2-based navigation approach using LiDAR and camera inputs.'],
  ['System architecture', 'I used LiDAR and camera data as environmental input. Sensor fusion and SLAM estimate the AGV position and generate a map, A* selects a global route, and a local planner adjusts the trajectory for obstacle avoidance. I passed navigation commands to the ESP32 motor-control layer, with the Jetson Orin Nano supporting the higher-level computing environment.'],
  ['Design process', 'I began with a 120 cm by 100 cm chassis concept and aluminium extrusion members. I designed custom brackets for the suspension, Unitree 4D LiDAR, and ZED 2i camera, then carried those decisions into fabrication, assembly, and system integration.'],
  ['Hardware and software', 'I used ROS2, LiDAR, camera-based machine vision, an ESP32, an NVIDIA Jetson Orin Nano, SolidWorks, Gazebo, SLAM, A* global planning, local obstacle avoidance, and YOLOv8 models for vision tasks.'],
  ['Technical specifications', 'I documented a 120 cm by 100 cm chassis using 45 by 45 mm and 40 by 80 mm aluminium profiles. I designed a suspension attachment with a 29.5 mm strut opening and M6 fasteners, plus a 100 mm by 60 mm LiDAR mount with M3 sensor fasteners and M4 chassis mounting holes.'],
  ['Testing and results', 'I documented a Gazebo simulation with static obstacles, a LiDAR and camera configuration aligned with the physical platform, and an integrated chassis with motor hubs, battery, emergency stop, wiring, camera, and LiDAR placement. The broader integrated-system chapter also records vision, access-control, dashboard, and motor-control testing.'],
  ['Challenges and solutions', 'I addressed hospital navigation requirements through LiDAR and camera sensing, SLAM, global and local planning, deliberate sensor placement, and a modular chassis that supports adjustment and maintenance.'],
  ['Key achievements', 'I produced a documented AGV chassis and navigation platform with custom mechanical mounts, a ROS2 navigation strategy, LiDAR and camera integration, and an embedded control path linking navigation commands to the vehicle motors.'],
  ['Lessons learned', 'I learned that mechanical dimensions, sensor placement, software architecture, and control interfaces must be designed together. The project also reinforced the importance of safety margins, stable mounts, cable management, and staged simulation before real-world deployment.'],
  ['Future improvements', 'I would validate the AGV with combined static and dynamic obstacles, refine localization and route planning, complete the secure payload compartments, tune the safety thresholds, and expand testing in hospital-like environments with representative loads and users.'],
];
