import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { Footer, PhotoSlot, SiteHeader } from '../../components';
import { experience } from '../../portfolio-data';

export function generateStaticParams() { return experience.map(item => ({ slug: item.slug })); }

export default async function ExperienceDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = experience.find(entry => entry.slug === slug) ?? experience[0];
  return <main><SiteHeader /><article className="experience-case-study"><div className="experience-case-top"><a className="back-link" href="/experience"><ArrowLeft size={16} /> Back to experience</a><span className="eyebrow">{item.slug.replaceAll('-', ' ').toUpperCase()} / EXPERIENCE</span></div><div className="experience-case-hero"><div><span className="eyebrow">{item.organization}</span><h1>{item.role}<br /><em>in context.</em></h1><p>{item.detail}</p><div className="case-meta"><span><strong>PERIOD</strong>{item.period}</span><span><strong>ROLE</strong>{item.role}</span></div>{item.progression && <div className="promotion-line"><span className="eyebrow">CAREER PROGRESSION</span><strong>{item.progression}</strong></div>}</div><PhotoSlot code="EXP / DETAIL" title={item.role} label={item.image ? 'INTERNSHIP REPORT PHOTO' : 'EXPERIENCE / PHOTO SLOT'} large accent="red" image={item.image} /></div><div className="experience-case-layout"><aside><span className="eyebrow">ON THIS EXPERIENCE</span><a href="#role">My role</a><a href="#tools">Tools and environment</a>{item.progression && <a href="#progression">Promotion path</a>}</aside><div className="experience-case-body"><section id="role"><span className="section-marker">/</span><h2>My role.</h2><p>{item.detail}</p></section><section id="tools"><span className="section-marker">/</span><h2>Tools and environment.</h2><p>I worked with {item.tools.split(' / ').join(', ')}. This role strengthened the way I translate technical requirements into clear actions, practical support, and reliable outcomes.</p></section>{item.progression && <section id="progression"><span className="section-marker">/</span><h2>Promotion path.</h2><p>{item.progression}. I earned that progression by taking on wider laboratory responsibility, supporting more students, and leading other assistants while keeping the engineering environment safe and useful.</p></section>}<a className="experience-next-link" href="/experience">Return to my experience archive <ArrowUpRight size={16} /></a></div></div></article><Footer /></main>;
}
